### PR TITLE
Update to Unexpected 11 (beta) and update peer dep to declare support for it

### PR DESCRIPTION
**Pull request by papandreou**
I wasn't sure if `package-lock.json` is checked in by mistake, but I updated that too.

### CODE REVIEW

**Comment by papandreou** [comment]
Ping @fgnass :)

**Comment by fgnass** [comment]
Merged. I added you as collaborator, so you don't have to wait that long next time. If you want I can add you on npm too.

**Comment by fgnass** [comment]
@papandreou Hi! Could you take a look why the tests failed after merging?

**Comment by papandreou** [comment]
Thanks for merging! You're welcome to add me on npm, too. My username is `papandreou` there as well 🤗

I have to admit that I don't actually use this module, but will take a look at the failing test.

**Comment by papandreou** [comment]
The same test failed when I retried, so it seems consistent.

I don't have a functional local test setup, but maybe the CI build of https://github.com/fgnass/unexpected-webdriver/commit/4efcd9dfa194e131b6c6e228dfbff5b83cf9dc96 will show what's up.

**Comment by papandreou** [comment]
Ah, seems like the `class` attribute comes out as `''`: https://travis-ci.org/fgnass/unexpected-webdriver/builds/565462922#L247-L249

I guess that makes it a bit hard to distinguish between an empty and a completely absent attribute 😟

Let's see if it's just `class` that works like that: https://travis-ci.org/fgnass/unexpected-webdriver/builds/565464548

**Comment by papandreou** [comment]
That worked, so maybe it's just `class` that changed behavior. In a browser, `element.getAttribute('class')` returns `null` when there's no `class` attribute, so it seems like a bug in WebDriver.

I guess it doesn't really make sense for unexpected-webdriver to try to paper over that. I suggest we "fix" it by just checking a different attribute in the test: https://github.com/fgnass/unexpected-webdriver/pull/2

**Comment by papandreou** [comment]
Released in 2.0.1.

**Pull request merged**
